/*
 * Nested Object
 * Nested Objct Sample.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package us.test.openapi.graphql.client;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkNestedObjectTest() {
        String nestedObjectName = null;
        List<String> nestedObjectTypes = null;
        String nestedObjectParakeetColor = null;
        Boolean nestedObjectParakeetSoundRepeater = null;
        Integer nestedObjectCount = null;
        Boolean nestedObjectEnable = null;
        api.checkNestedObject(nestedObjectName, nestedObjectTypes, nestedObjectParakeetColor, nestedObjectParakeetSoundRepeater, nestedObjectCount, nestedObjectEnable);

        // TODO: test validations
    }
}
